// מאגר נתונים ראשוני - שיכון ובינוי - תיק אתר IT
const INITIAL_SITES = [
  // אלן (7 אתרים)
  {
    id: "site-1",
    name: "מפעל בטון חולון",
    city: "חולון",
    region: "מרכז",
    notes: "",
    technician: "אלן",
    address: "אזור תעשייה, חולון",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מנהל אתר", role: "מנהל עבודה", phone: "050-0000001", email: "holon@shikunbinui.com" },
      { name: "איש קשר מקומי", role: "רכז תפעול", phone: "050-0000002", email: "" }
    ],
    itSpecs: {
      provider: "בזק בינלאומי / תשתית בזק",
      ipAddress: "192.168.10.1",
      subnet: "255.255.255.0",
      routerModel: "Fortinet FortiGate 60F",
      switches: "Cisco Catalyst 24P PoE",
      wifiAp: "2x UniFi U6-Lite",
      printerModel: "HP LaserJet Pro M428fdw",
      techNotes: "ארון תקשורת בחדר מנהל מפעל. נקודות רשת לשקילה ולמשרד."
    }
  },
  {
    id: "site-2",
    name: "פרשקובסקי הרצליה",
    city: "הרצליה",
    region: "מרכז",
    notes: "",
    technician: "אלן",
    address: "הרצליה פיתוח / גליל ים",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מנהל פרויקט", role: "מנהל פרויקט", phone: "052-1111111", email: "herzliya@shikunbinui.com" }
    ],
    itSpecs: {
      provider: "סלקום עסקים",
      ipAddress: "192.168.12.1",
      subnet: "255.255.255.0",
      routerModel: "MikroTik RB4011",
      switches: "1x 16 Port PoE",
      wifiAp: "UniFi AP-AC-Pro",
      printerModel: "Canon i-SENSYS MF445dw",
      techNotes: "משרדי הנהלה בקומה 2."
    }
  },
  {
    id: "site-3",
    name: "הוד השרון",
    city: "הוד השרון",
    region: "מרכז",
    notes: "משרד מכירות",
    technician: "אלן",
    address: "רחוב סוקולוב, הוד השרון",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מנהלת משרד מכירות", role: "מכירות ושיווק", phone: "054-2222222", email: "hod.sales@shikunbinui.com" }
    ],
    itSpecs: {
      provider: "הוט עסקים",
      ipAddress: "192.168.14.1",
      subnet: "255.255.255.0",
      routerModel: "FortiGate 40F",
      switches: "TP-Link 8P Gigabit",
      wifiAp: "Aruba Instant On AP11",
      printerModel: "Brother MFC-L3770CDW",
      techNotes: "משרד מכירות ייצוגי - כולל מסך תצוגה מחובר ל-NUC."
    }
  },
  {
    id: "site-4",
    name: "מפעל אספלט מודיעין",
    city: "ברקת",
    region: "מרכז",
    notes: "",
    technician: "אלן",
    address: "אזור תעשייה ברקת / מודיעין",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מנהל מפעל", role: "תפעול וייצור", phone: "050-3333333", email: "bareket@shikunbinui.com" }
    ],
    itSpecs: {
      provider: "תשתית סלולרית תעשייתית (סלקום / ראוטר Teltonika)",
      ipAddress: "192.168.16.1",
      subnet: "255.255.255.0",
      routerModel: "Teltonika RUT950 (LTE)",
      switches: "D-Link Industrial 8P",
      wifiAp: "Ubiquiti NanoStation LOCO M2",
      printerModel: "HP LaserJet P2035",
      techNotes: "חיבור עמדת שקילה תעשייתית ומצלמות LPR בכניסה."
    }
  },
  {
    id: "site-5",
    name: "מסילה מזרחית אלעד",
    city: "אלעד",
    region: "מרכז",
    notes: "",
    technician: "אלן",
    address: "אתר עבודה רכבת ישראל, סמוך לאלעד",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מהנדס אתר", role: "הנדסה ותשתיות", phone: "050-4444444", email: "elad.rail@shikunbinui.com" }
    ],
    itSpecs: {
      provider: "מודם סלולרי LTE חזק + אנטנה חיצונית",
      ipAddress: "192.168.18.1",
      subnet: "255.255.255.0",
      routerModel: "Teltonika RUTX11",
      switches: "8P PoE Switch",
      wifiAp: "UniFi Outdoor AP",
      printerModel: "HP All-In-One",
      techNotes: "קרוואן משרד שטח. חשמל מגנרטור - קיים אל-פסק UPS 1500VA."
    }
  },
  {
    id: "site-6",
    name: "מעונות רחובות",
    city: "רחובות",
    region: "מרכז \\ דרום",
    notes: "",
    technician: "אלן",
    address: "רחוב הרצל, רחובות",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מנהל עבודה", role: "פיקוח בינוי", phone: "052-5555555", email: "rehovot@shikunbinui.com" }
    ],
    itSpecs: {
      provider: "בזק סיבים",
      ipAddress: "192.168.20.1",
      subnet: "255.255.255.0",
      routerModel: "FortiGate 60F",
      switches: "Cisco SG250 24P",
      wifiAp: "2x UniFi AP",
      printerModel: "Lexmark MX521de",
      techNotes: "רשת משרדית + נקודות רשת למצלמות שטח."
    }
  },
  {
    id: "site-7",
    name: "יובלים",
    city: "נס ציונה",
    region: "מרכז \\ דרום",
    notes: "",
    technician: "אלן",
    address: "מתחם יובלים, נס ציונה",
    status: "פעיל",
    highlight: "",
    contacts: [
      { name: "מנהל אתר", role: "ניהול פרויקט", phone: "053-6666666", email: "yuvalim@shikunbinui.com" }
    ],
    itSpecs: {
      provider: "פרטנר סיבים",
      ipAddress: "192.168.22.1",
      subnet: "255.255.255.0",
      routerModel: "Check Point 1530",
      switches: "HP ProCurve 24G",
      wifiAp: "Aruba AP-22",
      printerModel: "HP LaserJet MFP",
      techNotes: "משרדי מנהלת פרויקט. גיבוי סלולרי אוטומטי מוגדר."
    }
  },

  // ברוך (39 אתרים)
  {
    id: "site-8",
    name: "משטרת שדרות",
    city: "שדרות",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "שדרות, מתחם תחנת המשטרה",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר שטח", role: "מנהל עבודה", phone: "050-7000001", email: "" }],
    itSpecs: { provider: "בזק עסקים + LTE", ipAddress: "192.168.30.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "16P PoE", wifiAp: "UniFi AP", printerModel: "Brother MFC", techNotes: "אתר מאובטח. נדרש תיאום מראש בכניסה." }
  },
  {
    id: "site-9",
    name: "רמת חובב",
    city: "רמת חובב",
    region: "דרום",
    notes: "בטיפול דודי קדם",
    technician: "ברוך",
    address: "פארק תעשיות נאות חובב",
    status: "פעיל",
    highlight: "red",
    contacts: [
      { name: "דודי קדם", role: "אחראי אתר ראשי", phone: "050-7000002", email: "dudi.k@shikunbinui.com" },
      { name: "מנהל תפעול", role: "תפעול שטח", phone: "052-7000003", email: "" }
    ],
    itSpecs: { provider: "בזק סיבים", ipAddress: "192.168.32.1", subnet: "255.255.255.0", routerModel: "Cisco ISR 1100", switches: "24P Cisco PoE", wifiAp: "3x UniFi AC-PRO", printerModel: "Canon ImageRunner", techNotes: "אתר בטיפול ישיר מול דודי קדם. דורש ציוד מגן אישי בכניסה למתחם." }
  },
  {
    id: "site-10",
    name: "מחלף קרית גת",
    city: "קרית גת",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "סמוך לכביש 6 / מחלף קרית גת",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל עבודה", role: "סלילה ותשתיות", phone: "050-7000004", email: "" }],
    itSpecs: { provider: "סלולרי Teltonika RUT955", ipAddress: "192.168.34.1", subnet: "255.255.255.0", routerModel: "Teltonika LTE", switches: "8 Port Industrial", wifiAp: "Ubiquiti Loco", printerModel: "HP DeskJet", techNotes: "קרוואן שטח סמוך לכביש." }
  },
  {
    id: "site-11",
    name: "אורים",
    city: "קיבוץ אורים",
    region: "דרום",
    notes: "אנרגיה",
    technician: "ברוך",
    address: "קיבוץ אורים, עוטף עזה",
    status: "פעיל",
    highlight: "red",
    contacts: [{ name: "מנהל פרויקט אנרגיה", role: "מנהל אתר סולארי", phone: "054-7000005", email: "solar.urim@company.co.il" }],
    itSpecs: { provider: "קו תמסורת / סלולרי מאובטח", ipAddress: "192.168.36.1", subnet: "255.255.255.0", routerModel: "Cisco Industrial", switches: "Moxa Industrial Switch", wifiAp: "UniFi Mesh", printerModel: "-", techNotes: "מתקן סולארי - תקשורת מול מערכת SCADA ובקרת ממירים." }
  },
  {
    id: "site-12",
    name: "צאלים",
    city: "צאלים",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "מתחם חוות צאלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר", role: "תפעול", phone: "050-7000006", email: "" }],
    itSpecs: { provider: "סלקום LTE", ipAddress: "192.168.38.1", subnet: "255.255.255.0", routerModel: "MikroTik hEX S", switches: "8P PoE", wifiAp: "UniFi AP", printerModel: "HP 404dn", techNotes: "משרד מכולה באתר." }
  },
  {
    id: "site-13",
    name: "ערד הארץ",
    city: "ערד",
    region: "דרום",
    notes: "מפעל ישן",
    technician: "ברוך",
    address: "אזור תעשייה ערד (ישן)",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מפעל ישן", role: "ייצור", phone: "052-7000007", email: "arad.old@company.co.il" }],
    itSpecs: { provider: "בזק VDSL", ipAddress: "192.168.40.1", subnet: "255.255.255.0", routerModel: "D-Link Business", switches: "16P 10/100/1000", wifiAp: "TP-Link Omada", printerModel: "HP LaserJet", techNotes: "תשתית ישנה - מתוכנן שדרוג ארון תקשורת." }
  },
  {
    id: "site-14",
    name: "ערד הארץ",
    city: "ערד",
    region: "דרום",
    notes: "מפעל חדש",
    technician: "ברוך",
    address: "פארק תעשיות ערד (חדש)",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מפעל חדש", role: "הנהלת מפעל", phone: "052-7000008", email: "arad.new@company.co.il" }],
    itSpecs: { provider: "בזק סיבים 1Gbps", ipAddress: "192.168.42.1", subnet: "255.255.255.0", routerModel: "FortiGate 80F", switches: "Aruba 48P PoE", wifiAp: "4x Aruba AP22", printerModel: "Ricoh IM C3000", techNotes: "תשתית חדישה - ארון תקשורת מסודר בקומה 1." }
  },
  {
    id: "site-15",
    name: "PV ניהול",
    city: "נתיבות",
    region: "דרום",
    notes: "אנרגיה",
    technician: "ברוך",
    address: "פארק תעשייה נעם, נתיבות",
    status: "פעיל",
    highlight: "red",
    contacts: [{ name: "רכז אנרגיה סולארית", role: "בקרת PV", phone: "054-7000009", email: "pv.netivot@company.co.il" }],
    itSpecs: { provider: "פרטנר סיבים + גיבוי סלולרי", ipAddress: "192.168.44.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "Cisco 24P", wifiAp: "UniFi AP-Pro", printerModel: "HP M428", techNotes: "מרכז שליטה סולארי - קווים רציפים לחוות פוטו-וולטאיות." }
  },
  {
    id: "site-16",
    name: "נבטים 18",
    city: "נבטים",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "סמוך לבסיס נבטים, כביש 25",
    status: "פעיל",
    highlight: "red",
    contacts: [{ name: "מנהל עבודה ראשי", role: "ניהול אתר", phone: "050-7000010", email: "" }],
    itSpecs: { provider: "תקשורת סלולרית כפולה (Dual SIM)", ipAddress: "192.168.46.1", subnet: "255.255.255.0", routerModel: "Teltonika RUTX12", switches: "8P PoE", wifiAp: "UniFi Long-Range", printerModel: "Brother MFC-L2710DW", techNotes: "אזור קליטה רגיש. אנטנות חיצוניות על תורן המשרד." }
  },
  {
    id: "site-17",
    name: "מפעל אספלט דרגות",
    city: "הר דרגות",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "מצוקי דרגות / ים המלח",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מפעל דרגות", role: "תפעול", phone: "050-7000011", email: "" }],
    itSpecs: { provider: "צלחת מיקרוגל / סלולרי", ipAddress: "192.168.48.1", subnet: "255.255.255.0", routerModel: "MikroTik NetMetal", switches: "8P Industrial", wifiAp: "UniFi Outdoor", printerModel: "HP LaserJet", techNotes: "תנאי סביבה מאובקים וחמים. ארון תקשורת אטום IP65 ממוזג." }
  },
  {
    id: "site-18",
    name: "פולדמיר- אורים",
    city: "גדרה",
    region: "דרום",
    notes: "לבדוק האם פעיל",
    technician: "ברוך",
    address: "גדרה / אורים",
    status: "בבדיקה",
    highlight: "yellow",
    contacts: [{ name: "איש קשר לבירור", role: "בירור סטטוס", phone: "053-7000012", email: "" }],
    itSpecs: { provider: "בבירור מול הנהלת פרויקטים", ipAddress: "192.168.50.1", subnet: "255.255.255.0", routerModel: "-", switches: "-", wifiAp: "-", printerModel: "-", techNotes: "יש לוודא האם האתר עודנו פעיל או שפורק והציוד הוחזר למחסן." }
  },
  {
    id: "site-19",
    name: "דיזיין פלוס",
    city: "באר שבע",
    region: "דרום",
    notes: "משרד ניהול",
    technician: "ברוך",
    address: "מרכז Design Plus, א.ת באר שבע",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהלת משרד", role: "ניהול משרד", phone: "054-7000013", email: "design.plus@company.co.il" }],
    itSpecs: { provider: "הוט עסקים 500M", ipAddress: "192.168.52.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "D-Link 16P", wifiAp: "2x UniFi Lite", printerModel: "Xerox VersaLink C405", techNotes: "משרד ניהול מסודר, 8 עמדות עבודה." }
  },
  {
    id: "site-20",
    name: "קמפוס מודיעין",
    city: "באר שבע",
    region: "דרום",
    notes: "אתר גדול",
    technician: "ברוך",
    address: "פארק ההייטק גב-ים, באר שבע",
    status: "פעיל",
    highlight: "grey",
    contacts: [
      { name: "מנהל פרויקט ראשי", role: "הנהלת הפרויקט", phone: "050-7000014", email: "campus.bs@company.co.il" },
      { name: "איש IT מקומי", role: "תמיכה שוטפת", phone: "052-7000015", email: "it.campus@company.co.il" }
    ],
    itSpecs: { provider: "בזק סיבים 1Gbps כפול + קו גיבוי פרטנר", ipAddress: "10.100.20.1", subnet: "255.255.255.0", routerModel: "FortiGate 100F HA Cluster", switches: "4x Cisco Catalyst 9200 48P", wifiAp: "12x Aruba AP505", printerModel: "3x Canon Multifunction", techNotes: "אתר גדול - 4 מפלסי משרדים, חדר שרתים מקומי עם מזגן כפול ו-UPS." }
  },
  {
    id: "site-21",
    name: "כבישים באר שבע",
    city: "באר שבע",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "כביש עוקף באר שבע / שדרות רגר",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מחלקת כבישים", role: "ביצוע", phone: "050-7000016", email: "" }],
    itSpecs: { provider: "סלולרי סלקום", ipAddress: "192.168.56.1", subnet: "255.255.255.0", routerModel: "Teltonika RUT240", switches: "8P Switch", wifiAp: "UniFi AP", printerModel: "HP LaserJet", techNotes: "קרוואן משרד נייד." }
  },
  {
    id: "site-22",
    name: "מפעל בטון באר-שבע",
    city: "באר שבע",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "עמק שרה, באר שבע",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מפעל בטון", role: "מנהל אתר", phone: "052-7000017", email: "beton.bs@company.co.il" }],
    itSpecs: { provider: "בזק תשתית", ipAddress: "192.168.58.1", subnet: "255.255.255.0", routerModel: "Check Point Quantum Spark", switches: "16P PoE", wifiAp: "UniFi Mesh", printerModel: "Brother HL-L5200DW", techNotes: "חיבור עמדת שקילת משאיות ומסופון נהגים." }
  },
  {
    id: "site-23",
    name: "תקשוב",
    city: "באר שבע",
    region: "דרום",
    notes: "אתר גדול",
    technician: "ברוך",
    address: "קריית התקשוב, ליד אוניברסיטת בן גוריון",
    status: "פעיל",
    highlight: "grey",
    contacts: [
      { name: "מהנדס ראשי", role: "מנהל מתחם תקשוב", phone: "050-7000018", email: "tikshuv@company.co.il" },
      { name: "רכז רשתות", role: "IT שטח", phone: "054-7000019", email: "" }
    ],
    itSpecs: { provider: "תשתית סיב אופטי עצמאי + FortiGate", ipAddress: "10.200.10.1", subnet: "255.255.254.0", routerModel: "FortiGate 200E", switches: "6x Cisco Catalyst 3850", wifiAp: "16x Cisco Aironet", printerModel: "Konica Minolta Bizhub C360i", techNotes: "אתר גדול ומורכב. תקני אבטחה מחמירים. גישה עם אישור מראש." }
  },
  {
    id: "site-24",
    name: "אשלים",
    city: "אשלים",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "פארק סולארי אשלים, נגב מערבי",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר תרמו-סולארי", role: "תפעול מתקן", phone: "052-7000020", email: "ashalim@company.co.il" }],
    itSpecs: { provider: "סיב אופטי תעשייתי + גיבוי לווייני/סלולרי", ipAddress: "192.168.62.1", subnet: "255.255.255.0", routerModel: "Cisco Industrial 3000", switches: "Industrial Ruggedized 24P", wifiAp: "Industrial Outdoor AP", printerModel: "HP MFP", techNotes: "תנאי חום קיצוניים. מערכות סולאריות מחוברות ל-VLAN ייעודי." }
  },
  {
    id: "site-25",
    name: "מרינה אשדוד",
    city: "אשדוד",
    region: "דרום",
    notes: "אתר בהקמה",
    technician: "ברוך",
    address: "מתחם המרינה, אשדוד",
    status: "בהקמה",
    highlight: "",
    contacts: [{ name: "מנהל בינוי מרינה", role: "בינוי ופיתוח", phone: "050-7000021", email: "" }],
    itSpecs: { provider: "חיבור זמני LTE", ipAddress: "192.168.64.1", subnet: "255.255.255.0", routerModel: "Teltonika RUT950", switches: "8P PoE Switch", wifiAp: "UniFi AP", printerModel: "Canon Multifunction", techNotes: "אתר בהקמה. טרם חובר סיב קבוע. הזמנת בזק פתוחה מספר 948271." }
  },
  {
    id: "site-26",
    name: "תחנת כח אתגל",
    city: "אשדוד",
    region: "דרום",
    notes: "",
    technician: "ברוך",
    address: "אזור תעשייה צפוני, אשדוד",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל תחנה", role: "ניהול אתר אנרגיה", phone: "052-7000022", email: "etgal@company.co.il" }],
    itSpecs: { provider: "בזק קווי תמסורת", ipAddress: "192.168.66.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "24P Cisco PoE", wifiAp: "2x UniFi AP", printerModel: "HP LaserJet Pro", techNotes: "מתקן תשתיות אנרגיה. גישה עם נעלי עבודה ואפוד זוהר." }
  },
  {
    id: "site-27",
    name: "תמך 1",
    city: "תל אביב יפו",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "מתחם נתב\"ג / תל אביב",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר תמך", role: "ניהול עבודה", phone: "050-7000023", email: "" }],
    itSpecs: { provider: "בזק סיבים", ipAddress: "192.168.68.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "16P Gigabit", wifiAp: "UniFi 6 Lite", printerModel: "Brother MFC", techNotes: "משרדי פיקוח והנדסה." }
  },
  {
    id: "site-28",
    name: "תע\"ש השלום",
    city: "תל אביב יפו",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "דרך השלום, תל אביב",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מהנדס ראשי", role: "ניהול פרויקט", phone: "054-7000024", email: "taas.hashalom@company.co.il" }],
    itSpecs: { provider: "סלקום סיבים 500M", ipAddress: "192.168.70.1", subnet: "255.255.255.0", routerModel: "Check Point 1550", switches: "24P Cisco PoE", wifiAp: "3x UniFi AC-PRO", printerModel: "Xerox WorkCentre", techNotes: "משרדים מרכזיים באתר הבנייה." }
  },
  {
    id: "site-29",
    name: "בן גוריון - רמלה",
    city: "רמלה",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "שדרות בן גוריון, רמלה",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל עבודה", role: "מנהל אתר", phone: "052-7000025", email: "" }],
    itSpecs: { provider: "הוט עסקים", ipAddress: "192.168.72.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "8P PoE", wifiAp: "UniFi Lite", printerModel: "HP MFP", techNotes: "ארון תקשורת בחדר ישיבות." }
  },
  {
    id: "site-30",
    name: "מפעל בטון - נחשונים",
    city: "ראש העין / נחשונים",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "קיבוץ נחשונים / מחצבת נחשונים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מפעל נחשונים", role: "תפעול ייצור", phone: "050-7000026", email: "nachshonim@company.co.il" }],
    itSpecs: { provider: "בזק VDSL + LTE גיבוי", ipAddress: "192.168.74.1", subnet: "255.255.255.0", routerModel: "MikroTik RB750Gr3", switches: "16P D-Link", wifiAp: "UniFi Long-Range", printerModel: "HP LaserJet 400", techNotes: "מפעל בטון מרכזי. חיבור למערכת בקרה ושקילה." }
  },
  {
    id: "site-31",
    name: "מקטע D",
    city: "מחלף לוד",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "סמוך למחלף לוד / כביש 40",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מקטע", role: "סלילה", phone: "050-7000027", email: "" }],
    itSpecs: { provider: "סלולרי LTE Teltonika", ipAddress: "192.168.76.1", subnet: "255.255.255.0", routerModel: "Teltonika RUT950", switches: "8P Gigabit", wifiAp: "Ubiquiti AP", printerModel: "Brother Portable", techNotes: "משרד קרוואן בשטח." }
  },
  {
    id: "site-32",
    name: "431 - מודיעין",
    city: "מודיעין",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "כביש 431 לכיוון מודיעין",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מקטע 431", role: "תשתיות", phone: "052-7000028", email: "" }],
    itSpecs: { provider: "סלקום LTE", ipAddress: "192.168.78.1", subnet: "255.255.255.0", routerModel: "Teltonika RUTX11", switches: "8P Switch", wifiAp: "UniFi AP", printerModel: "HP LaserJet", techNotes: "אתר שטח לאורך התוואי." }
  },
  {
    id: "site-33",
    name: "בן שמן",
    city: "לוד",
    region: "מרכז",
    notes: "משרדי האתר",
    technician: "ברוך",
    address: "מתחם גני יער / בן שמן, לוד",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל משרדי האתר", role: "הנהלת אתר", phone: "050-7000029", email: "ben.shemen.site@company.co.il" }],
    itSpecs: { provider: "בזק סיבים 500M", ipAddress: "192.168.80.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "24P Cisco PoE", wifiAp: "3x UniFi 6 Lite", printerModel: "Canon ImageRunner 2630", techNotes: "משרדים ראשיים של מתחם בן שמן." }
  },
  {
    id: "site-34",
    name: "בן שמן",
    city: "לוד",
    region: "מרכז",
    notes: "משרדי ההשכרה",
    technician: "ברוך",
    address: "מתחם שיווק והשכרה, בן שמן לוד",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהלת השכרות", role: "שיווק והשכרה", phone: "054-7000030", email: "rent.benshemen@company.co.il" }],
    itSpecs: { provider: "שלוחה מ-LAN משרדי האתר (Fiber Link)", ipAddress: "192.168.80.50", subnet: "255.255.255.0", routerModel: "Cisco Small Business", switches: "16P Gigabit", wifiAp: "2x Aruba AP22", printerModel: "HP Color LaserJet MFP", techNotes: "מחובר בסיב אופטי ישיר למשרדי האתר (site-33)." }
  },
  {
    id: "site-35",
    name: "מכבי בית שמש",
    city: "בית שמש",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "רחוב נחל שורק, בית שמש",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר", role: "בינוי", phone: "052-7000031", email: "" }],
    itSpecs: { provider: "בזק VDSL", ipAddress: "192.168.82.1", subnet: "255.255.255.0", routerModel: "D-Link DSL Router", switches: "8P PoE", wifiAp: "UniFi AP", printerModel: "Brother MFC-L2700", techNotes: "אתר בינוי מוסדי." }
  },
  {
    id: "site-36",
    name: "מלון פאלס",
    city: "תל אביב יפו",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "טיילת תל אביב / הירקון",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מהנדס פרויקט מלון", role: "פרויקטים", phone: "050-7000032", email: "palace.tlv@company.co.il" }],
    itSpecs: { provider: "פרטנר סיבים 1Gbps", ipAddress: "192.168.84.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "2x Cisco 24P PoE", wifiAp: "4x UniFi AP-AC-PRO", printerModel: "Canon iR-ADV DX", techNotes: "אתר שימור ובינוי יוקרתי." }
  },
  {
    id: "site-37",
    name: "הירקון 2",
    city: "תל אביב יפו",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "רחוב הירקון 2, תל אביב",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל עבודה", role: "ביצוע", phone: "052-7000033", email: "" }],
    itSpecs: { provider: "הוט עסקים", ipAddress: "192.168.86.1", subnet: "255.255.255.0", routerModel: "MikroTik hEX", switches: "16P Switch", wifiAp: "UniFi 6 Lite", printerModel: "HP LaserJet MFP", techNotes: "משרדי הנהלת אתר בבניין סמוך." }
  },
  {
    id: "site-38",
    name: "אופק רחב",
    city: "רמלה",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "מחנה רחבעם (מפקדת אופק רחב), רמלה",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "קצין פרויקט / מנהל", role: "הנדסה צבאית", phone: "050-7000034", email: "ofek.ramla@company.co.il" }],
    itSpecs: { provider: "בזק סיבים ייעודיים", ipAddress: "10.50.10.1", subnet: "255.255.255.0", routerModel: "Check Point Quantum Spark", switches: "2x Cisco Catalyst 2960", wifiAp: "UniFi Enterprise", printerModel: "Lexmark MS821", techNotes: "מתקן ביטחוני. כניסה עם תעודת זהות ואישור בטחוני בלבד." }
  },
  {
    id: "site-39",
    name: "צומת סביון",
    city: "סביון",
    region: "מרכז",
    notes: "עתידי",
    technician: "ברוך",
    address: "צומת סביון / כביש 461",
    status: "עתידי",
    highlight: "yellow",
    contacts: [{ name: "מתאם פרויקטים", role: "תכנון", phone: "053-7000035", email: "planning@company.co.il" }],
    itSpecs: { provider: "טרם חובר (מתוכנן סיב בזק)", ipAddress: "192.168.88.1", subnet: "255.255.255.0", routerModel: "מתוכנן FortiGate 40F", switches: "מתוכנן 16P PoE", wifiAp: "מתוכנן UniFi AP", printerModel: "-", techNotes: "פרויקט עתידי. עלייה לקרקע מתוכננת לרבעון הבא." }
  },
  {
    id: "site-40",
    name: "מפעל בטון ראש העין",
    city: "נחשונים",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "פארק אפק / מחצבת ראש העין",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל תפעול מפעל", role: "תפעול", phone: "050-7000036", email: "" }],
    itSpecs: { provider: "בזק VDSL עסקי", ipAddress: "192.168.90.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "16P Gigabit", wifiAp: "UniFi AP", printerModel: "HP LaserJet", techNotes: "עמדת שקילה אוטומטית ומצלמות זיהוי לוחיות." }
  },
  {
    id: "site-41",
    name: "בן שמן",
    city: "לוד",
    region: "מרכז",
    notes: "משרדי האתר",
    technician: "ברוך",
    address: "לוד - מתחם גני יער מזרח",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל עבודה מתחם ב'", role: "בינוי", phone: "052-7000037", email: "" }],
    itSpecs: { provider: "בזק סיבים", ipAddress: "192.168.92.1", subnet: "255.255.255.0", routerModel: "MikroTik RB4011", switches: "24P PoE Switch", wifiAp: "2x UniFi 6 Pro", printerModel: "Brother MFC-L8690CDW", techNotes: "משרד שטח מתחם ב'." }
  },
  {
    id: "site-42",
    name: "ריקטק בן שמן",
    city: "לוד",
    region: "מרכז",
    notes: "בהקמה",
    technician: "ברוך",
    address: "מתחם ריקטק, אזור לוד / בן שמן",
    status: "בהקמה",
    highlight: "",
    contacts: [{ name: "מנהל הקמת ריקטק", role: "הקמה והנדסה", phone: "054-7000038", email: "" }],
    itSpecs: { provider: "סלולרי זמני Teltonika", ipAddress: "192.168.94.1", subnet: "255.255.255.0", routerModel: "Teltonika RUT950", switches: "8P PoE Switch", wifiAp: "UniFi AP", printerModel: "HP All-In-One", techNotes: "אתר בשלבי הקמה ראשוניים. הזמנת תשתית קבועה בטיפול." }
  },
  {
    id: "site-43",
    name: "מפעל בטון בני ברק",
    city: "בני ברק",
    region: "מרכז",
    notes: "",
    technician: "ברוך",
    address: "רחוב הירקון / א.ת בני ברק",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מפעל ב\"ב", role: "מנהל עבודה", phone: "050-7000039", email: "beton.bb@company.co.il" }],
    itSpecs: { provider: "הוט עסקים + סלקום גיבוי", ipAddress: "192.168.96.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "16P Cisco", wifiAp: "UniFi Long Range", printerModel: "Brother HL-L5100DN", techNotes: "מפעל מרכזי בבני ברק. ארון תקשורת נעול בחדר סדרן." }
  },
  {
    id: "site-44",
    name: "אור יהודה - עולם",
    city: "אור יהודה",
    region: "מרכז",
    notes: "אתר הבניה",
    technician: "ברוך",
    address: "מתחם O-PARK, אור יהודה",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל בינוי O-World", role: "מנהל אתר", phone: "052-7000040", email: "" }],
    itSpecs: { provider: "פרטנר סיבים", ipAddress: "192.168.98.1", subnet: "255.255.255.0", routerModel: "Check Point 1530", switches: "24P PoE Switch", wifiAp: "3x UniFi 6 Lite", printerModel: "HP LaserJet MFP", techNotes: "משרדי הנהלת אתר הבנייה." }
  },
  {
    id: "site-45",
    name: "אור יהודה - עולם",
    city: "אור יהודה",
    region: "מרכז",
    notes: "משרד מכירות",
    technician: "ברוך",
    address: "מתחם O-PARK משרד מכירות, אור יהודה",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהלת מכירות O-World", role: "שיווק", phone: "054-7000041", email: "sales.oy@company.co.il" }],
    itSpecs: { provider: "בזק סיבים 1Gbps", ipAddress: "192.168.100.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "16P Gigabit", wifiAp: "2x Aruba AP22", printerModel: "Canon Color ImageRunner", techNotes: "משרד מכירות יוקרתי, רשת אלחוטית לאורחים (Guest WiFi)." }
  },
  {
    id: "site-46",
    name: "ריקטק יבנה",
    city: "יבנה",
    region: "מרכז \\ דרום",
    notes: "",
    technician: "ברוך",
    address: "פארק תעשיות יבנה דרום",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל מתחם ריקטק יבנה", role: "תפעול", phone: "050-7000042", email: "ricktech.yavne@company.co.il" }],
    itSpecs: { provider: "בזק סיבים 500M", ipAddress: "192.168.102.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "24P Cisco PoE", wifiAp: "UniFi AP-Pro", printerModel: "Brother MFC", techNotes: "מחסן מרכזי ומשרדי הנהלה." }
  },

  // חזי (7 אתרים)
  {
    id: "site-47",
    name: "פייר קניג",
    city: "ירושלים",
    region: "ירושלים",
    notes: "",
    technician: "חזי",
    address: "רחוב פייר קניג, תלפיות, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר תלפיות", role: "ניהול פרויקט", phone: "050-8000001", email: "pierre.koenig@company.co.il" }],
    itSpecs: { provider: "בזק סיבים 1Gbps", ipAddress: "192.168.110.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "24P Cisco Catalyst", wifiAp: "3x UniFi AP-AC", printerModel: "Canon iR-ADV", techNotes: "משרדי פרויקט תלפיות. ארון תקשורת בקומה 1." }
  },
  {
    id: "site-48",
    name: "הגבעה הצרפתית",
    city: "ירושלים",
    region: "ירושלים",
    notes: "מנורה",
    technician: "חזי",
    address: "מחלף הגבעה הצרפתית / שדרות בר-לב, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מהנדס מנהרות / מנורה", role: "פיקוח הנדסי", phone: "052-8000002", email: "french.hill@company.co.il" }],
    itSpecs: { provider: "פרטנר סיבים + סלולרי גיבוי", ipAddress: "192.168.112.1", subnet: "255.255.255.0", routerModel: "Check Point 1550", switches: "24P Industrial PoE", wifiAp: "2x UniFi Mesh", printerModel: "HP LaserJet Pro MFP", techNotes: "פרויקט מנהרות הגבעה הצרפתית. מחובר למערכות תאורה ובקרה של מנורה." }
  },
  {
    id: "site-49",
    name: "מנת\"י - רמזורים",
    city: "ירושלים",
    region: "ירושלים",
    notes: "",
    technician: "חזי",
    address: "מתחם בקרת תנועה מנת\"י, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל פרויקט רמזורים", role: "בקרה ורמזור", phone: "054-8000003", email: "manti.jer@company.co.il" }],
    itSpecs: { provider: "בזק קווי תמסורת ייעודיים", ipAddress: "10.30.50.1", subnet: "255.255.255.0", routerModel: "Cisco ISR 4331", switches: "3x Cisco Ruggedized 24P", wifiAp: "UniFi AP", printerModel: "HP M428dw", techNotes: "מרכז בקרת רמזורים ותנועה. רשת מבודדת ומאובטחת." }
  },
  {
    id: "site-50",
    name: "קפיטל בליליוס",
    city: "ירושלים",
    region: "ירושלים",
    notes: "",
    technician: "חזי",
    address: "רחוב יפו / מתחם בליליוס, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל בינוי מתחם", role: "מנהל עבודה", phone: "050-8000004", email: "capital.b@company.co.il" }],
    itSpecs: { provider: "סלקום סיבים 500M", ipAddress: "192.168.116.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "16P Gigabit PoE", wifiAp: "2x UniFi 6 Lite", printerModel: "Brother MFC-L3750CDW", techNotes: "משרדי מנהלת פרויקט קפיטל." }
  },
  {
    id: "site-51",
    name: "מגדלי ברגר",
    city: "ירושלים",
    region: "ירושלים",
    notes: "",
    technician: "חזי",
    address: "שערי העיר / רחוב יפו, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל פרויקט ברגר", role: "ניהול בינוי", phone: "052-8000005", email: "berger.towers@company.co.il" }],
    itSpecs: { provider: "הוט עסקים סיבים", ipAddress: "192.168.118.1", subnet: "255.255.255.0", routerModel: "FortiGate 60F", switches: "24P Cisco PoE", wifiAp: "3x Aruba Instant On", printerModel: "Konica Minolta C250i", techNotes: "משרדי הפרויקט בקומה 4." }
  },
  {
    id: "site-52",
    name: "משרד מכירות - יהודה שלום",
    city: "ירושלים",
    region: "ירושלים",
    notes: "",
    technician: "חזי",
    address: "רחוב יהודה שלום, ארנונה, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהלת מכירות ארנונה", role: "שיווק ומכירות", phone: "054-8000006", email: "sales.jer@company.co.il" }],
    itSpecs: { provider: "בזק סיבים 1Gbps", ipAddress: "192.168.120.1", subnet: "255.255.255.0", routerModel: "Check Point 1530", switches: "8P PoE Switch", wifiAp: "2x UniFi 6 Pro", printerModel: "Brother Color Laser", techNotes: "משרד מכירות פעיל - כולל טאבלטים לאנשי מכירות ומסכי הדגמה." }
  },
  {
    id: "site-53",
    name: "הנטקה",
    city: "ירושלים",
    region: "ירושלים",
    notes: "",
    technician: "חזי",
    address: "רחוב הנטקה, קרית היובל, ירושלים",
    status: "פעיל",
    highlight: "",
    contacts: [{ name: "מנהל אתר הנטקה", role: "פיקוח ובנייה", phone: "050-8000007", email: "hantke@company.co.il" }],
    itSpecs: { provider: "פרטנר סיבים", ipAddress: "192.168.122.1", subnet: "255.255.255.0", routerModel: "FortiGate 40F", switches: "16P PoE Switch", wifiAp: "UniFi 6 Lite", printerModel: "HP LaserJet MFP", techNotes: "משרדי אתר התחדשות עירונית." }
  }
];

const TECHNICIANS_META = {
  "אלן": {
    name: "אלן",
    role: "טכנאי שטח - מרכז",
    phone: "050-1234561",
    email: "alan@company.co.il",
    color: "blue",
    avatarBg: "from-blue-600 to-indigo-600",
    badgeBg: "bg-blue-100 text-blue-800 border-blue-200"
  },
  "ברוך": {
    name: "ברוך",
    role: "טכנאי שטח - דרום ומרכז",
    phone: "050-1234562",
    email: "baruch@company.co.il",
    color: "emerald",
    avatarBg: "from-emerald-600 to-teal-600",
    badgeBg: "bg-emerald-100 text-emerald-800 border-emerald-200"
  },
  "חזי": {
    name: "חזי",
    role: "טכנאי שטח - ירושלים והסביבה",
    phone: "050-1234563",
    email: "hezi@company.co.il",
    color: "amber",
    avatarBg: "from-amber-500 to-orange-600",
    badgeBg: "bg-amber-100 text-amber-800 border-amber-200"
  }
};
